"""Core context and canonical-schema contracts."""

from .audit import ArtifactDigest, digest_artifact, write_report_sidecar
from .context import (
    BackgroundContext,
    BiosphereProfile,
    ContextHint,
    FormatProfile,
    InventoryContext,
    TechnosphereProfile,
    VersionResolution,
    resolve_migration_series,
    resolve_profile_migration_series,
)
from .pipeline import InventoryPipeline
from .policies import ConversionPolicy, MigrationPolicy, PolicyAction
from .reports import (
    Change,
    Issue,
    Loss,
    OperationKind,
    OperationReport,
    OperationResult,
    Severity,
    StageKind,
    StageReport,
)
from .schema import (
    CANONICAL_SCHEMA_VERSION,
    CanonicalDataset,
    CanonicalExchange,
    CanonicalInventory,
    CanonicalParameter,
    DatasetIdentity,
    ExchangeIdentity,
    ExtensionMap,
    Uncertainty,
)

__all__ = (
    "BackgroundContext",
    "ArtifactDigest",
    "BiosphereProfile",
    "CANONICAL_SCHEMA_VERSION",
    "CanonicalDataset",
    "CanonicalExchange",
    "CanonicalInventory",
    "CanonicalParameter",
    "Change",
    "ConversionPolicy",
    "ContextHint",
    "DatasetIdentity",
    "ExchangeIdentity",
    "ExtensionMap",
    "FormatProfile",
    "InventoryContext",
    "InventoryPipeline",
    "Issue",
    "Loss",
    "MigrationPolicy",
    "OperationKind",
    "OperationReport",
    "OperationResult",
    "PolicyAction",
    "Severity",
    "StageKind",
    "StageReport",
    "TechnosphereProfile",
    "Uncertainty",
    "VersionResolution",
    "resolve_migration_series",
    "resolve_profile_migration_series",
    "digest_artifact",
    "write_report_sidecar",
)
