{% set version = environ.get("VERSION", "0.0.0") %}

package:
  name: brightpath
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv
  script_env:
    - VERSION
    - CONDA_BLD_PATH

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - wheel
    - prettytable >=3
    - pyyaml
  run:
    - python >=3.9
    - prettytable >=3
    - pyyaml
    # keep optional deps (e.g., bw2io) OUT of run unless needed at import time

test:
  imports:
    - brightpath
    - yaml  # <-- module name, not "pyyaml"
  requires:
    - pytest  # lightweight, optional

about:
  home: https://github.com/romainsacchi/brightpath
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Convert Brightway2/3 life-cycle inventories to SimaPro 9.x.'
